apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-local
spec:
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
