apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azure-file-share
spec:
  storageClassName: azurefile
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
