# ansible-playbook configure-tomcat8.yml -b
---
- name: configure tomcat8 on all managed nodes
  hosts: all
  tasks: 
    - name: Install tomcat8
      apt:
        name: tomcat8 
        state: present 
        update_cache: yes
    - name: change tomcat port to 9090
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat8/server.xml
    - name: restart tomcat8
      service:
        name: tomcat8 
        state: restarted
    - name: pause for 10 seconds
      pause:
        seconds: 10
    - name: check romcat8 url response of any one server
      uri:
        url: http://<ipaddress>:9090
        status: 200
...
