--- 
- name: setuop of docker for ansible
  hosts: all
  tasks:
    - name: install python-pip
      apt:
        name: pytjon-pip
        state: present 
        update_cache: yes
    - name: download docker & install docker-py
      shell: "{{item}}"
      with_items:
        - curl -fsSL https://get.docker.com -o get-docker.sh
        - sh get-docker.sh 
        - pip install docker-py
...
        