apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv-local
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/test-pv-local
